### ISSUE TITLE
Unit Test Game Page BE

### ISSUE THREAD

**Issue by hoatuyet423** [CSE110-Team17/cse110-sp23-group17#29]
### Requirements:
- [ ] Create a unit test to check if the cards array parse from json is correct
- [ ] Create a unit test to check if the function isInArray work as desired
- [ ] Create a unit test to check if the function play work as desire (check hp bar, image path, choosenCards array)

### Code-dependency:
- game.js

### Issue done criteria:
- All unit tests is made and the code pass all of them,

**Comment by mickjeon** [comment]
Merged with Pull Request #46 instead
