### ISSUE TITLE
Unit Test Result Page BE

### ISSUE THREAD

**Issue by hoatuyet423** [CSE110-Team17/cse110-sp23-group17#30]
### Requirements: 
- [ ] Create a unit test to check if chosenCards is parse correctly 
- [ ] Create a unit test to check function updateMobileCard (check if image path and text show correctly)
- [ ] Create a unit test to check function updateButtonVisibility (check for both case: desktop and mobile)

### Code-dependency:
- result.js 

### Issue done criteria:
- Unit tests is created and all passed

**Comment by mickjeon** [comment]
Closed with Pull Request #46
