### ISSUE TITLE
fix linting errors in js files

### ISSUE THREAD

**Issue by thekangster** [CSE110-Team17/cse110-sp23-group17#48]
### Assign to: Back-end team
<img width="1106" alt="Screenshot 2023-05-27 at 5 38 40 PM" src="https://github.com/CSE110-Team17/cse110-sp23-group17/assets/79072442/4d414858-761d-4478-91eb-52804e7fb7a3">

### Issue Done Criteria:
- [ ] fixed linting errors described above

**Comment by mickjeon** [comment]
Resolved with PR #64
