### ISSUE TITLE
New Game Play Feature

### ISSUE THREAD

**Issue by hoatuyet423** [CSE110-Team17/cse110-sp23-group17#54]
### Requirements:
- [x] There is a progress bar that go back and front. When click a card, the value of the progress bar will be the damage. 
- [x] Fix message to modal box (?)
- [x] Update HP accordingly
- [x] Add message from tarot reader
- [x] remove hp bar and opponent
- [ ] add sad and happy face next to luck bar

### Code-dependency: 
- game.js 
- game.html 
- 
### Issue done criteria:
- The new game can be played perfectly

**Comment by mickjeon** [comment]
Merge with PR #73
