### ISSUE TITLE
Database update

### ISSUE THREAD

**Issue by hoatuyet423** [CSE110-Team17/cse110-sp23-group17#65]
### Requirements:
- [x] Change it from json to js
- [x] Add shorterm description and also phrase for the tarot teller in game page (let me know if you want help to come up with this)
- [x]  junit tests for gameplay

### Code-dependency:
- tarot.js
- game.js
- game.test.js

### Issue done criteria:
- Database is change and is accessible by all members
- Gameplay are tested

**Comment by mickjeon** [comment]
Merged with PR #82
