### ISSUE TITLE
Result Pgae FE New Features

### ISSUE THREAD

**Issue by hoatuyet423** [CSE110-Team17/cse110-sp23-group17#67]
### Requirements:
- [x] Update so that it will only display 4 cards.
- [x] Update margin
- [x] Update the result page UI so it show shorterm and long term

### Code-dependency:
- result.html 
- result.js

### Issue done criteria:
- result page now show shorterm and long term fortune
- work on both desktop and mobile

**Comment by Maryamkusman** [comment]
I accidently did my own implentaition on this. But we will take Kristens implementation!!

**Comment by mickjeon** [comment]
Merged with PR #63
