### ISSUE TITLE
Results Page Card Layout and Buttons

### ISSUE THREAD

**Issue by KristinEbu** [CSE110-Team17/cse110-sp23-group17#77]
### Requirements:
- [x] try to prevent scrolling (2 different ways: have all card images lined up with descriptions below them or have 2 cards with their descriptions on one row)
- [x] add a button to the home page matching the button design from index.css
- [ ] try to match the next and previous button with the button style from index.css as well to see if it looks better 

### Deadline:
Thursday 6/8

### Code-dependency:
results.js

### Issue done criteria:
- [x] requirements above are met

**Comment by mickjeon** [comment]
Merged with PR #81
